### ISSUE TITLE
Add Screenshot field to the Feedback db 

### ISSUE THREAD

**Issue by naman** [IIIT-Delhi/jobport#18]
add an image field to the model

**Comment by suryatejreddy** [comment]
Once a user uploads the screenshot, which directory should it be saved to in the server?

**Comment by naman** [comment]
@suryatejreddy you can choose either 
store in a particular folder, or in the database itself

**Comment by naman** [comment]
@suryatejreddy awesome! did you try to run it? If it works, we are good to go. 
PS: send a PR with your fork.
