### ISSUE TITLE
Move to https using letsencrypt 

### ISSUE THREAD

**Issue by naman** [IIIT-Delhi/jobport#34]

**Comment by theparadoxer02** [comment]
Will it need server access ?
If not i would like to work on this issue 
also what are your views over this ?
https://www.abidibo.net/blog/2016/10/07/securing-django-lets-encrypt/

**Comment by naman** [comment]
Yes, it will need server access.

**Comment by Priyansh2001here** [comment]
I do need server acess i can work on it
