### ISSUE TITLE
Fix Upload CGPA UI

### ISSUE THREAD

**Issue by naman** [IIIT-Delhi/jobport#37]
![screenshot from 2016-10-29 12 32 56](https://cloud.githubusercontent.com/assets/5255299/19827861/d9c7aef6-9dd3-11e6-84c3-00c582e300fb.png)

**Comment by dudraj** [comment]
@naman can I work on this project.

**Comment by naman** [comment]
https://github.com/IIIT-Delhi/jobport/pull/38
